require: rubocop-rspec

FileName:
  Exclude:
    - lib/lita-pagerduty.rb

LineLength:
  Max: 130

Metrics/BlockLength:
  Max: 175

RSpec/MessageSpies:
  EnforcedStyle: receive

RSpec/VerifiedDoubles:
  Enabled: false

RSpec/MultipleExpectations:
  Max: 2
